name: ${PROJECT_NAME}  # ใช้ตัวแปรจาก .env เพื่อกำหนดชื่อโปรเจค

services:
  # 1. ฐานข้อมูล (Database)
  db-server:
    image: mariadb:10.6
    container_name: ${MY_USERNAME}-db
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: app_user
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_pass
    networks:
      - backend-zone
    volumes:
      - db-storage:/var/lib/mysql
      # ดึงไฟล์ seed-data.sql เข้าไปรันเพื่อสร้างตารางและข้อมูลตอนเปิดคอนเทนเนอร์
      - ./seed-data.sql:/docker-entrypoint-initdb.d/seed-data.sql
    secrets:
      - db_root_pass
      - db_user_pass

  # 2. ส่วนประมวลผล (Backend)
  backend-php:
    image: bitnami/php-fpm:latest
    container_name: ${MY_USERNAME}-php
    restart: always
    volumes:
      # ชี้ไปที่โฟลเดอร์ src ตามรูปของคุณ
      - ./src:/var/www/html
    networks:
      - backend-zone
    secrets:
      - db_user_pass

  # 3. ส่วนรับงานหน้าบ้าน (Web Proxy)
  web-proxy:
    image: nginx:latest
    container_name: ${MY_USERNAME}-web
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      # ชี้ไปที่โฟลเดอร์ src ตามรูปของคุณ
      - ./src:/var/www/html
    configs:
      - source: my-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend-zone
      - backend-zone
    depends_on:
      - backend-php

  # 4. ส่วนจัดการฐานข้อมูล (phpMyAdmin)
  db-management:
    image: phpmyadmin:latest
    container_name: ${MY_USERNAME}-pma
    restart: always
    environment:
      PMA_HOST: db-server
      PMA_PASSWORD_FILE: /run/secrets/db_root_pass
    ports:
      - "${PMA_PORT}:80"
    networks:
      - backend-zone
    depends_on:
      - db-server
    secrets:
      - db_root_pass

# --------------------------------------------------
# ส่วนประกาศทรัพยากรส่วนกลาง (Top-level Elements)
# --------------------------------------------------

networks:
  frontend-zone:
    driver: bridge
  backend-zone:
    driver: bridge

volumes:
  db-storage:

configs:
  my-nginx-conf:
    # แก้ชื่อไฟล์ให้ตรงกับโฟลเดอร์ nginx ของคุณ
    file: ./nginx/my-nginx.conf

secrets:
  db_root_pass:
    # แก้ path ให้เข้าไปในโฟลเดอร์ secret และใช้นามสกุล .txt ตามรูป
    file: ./secret/.db_root_pass.txt
  db_user_pass:
    # แก้ path ให้เข้าไปในโฟลเดอร์ secret และใช้นามสกุล .txt ตามรูป
    file: ./secret/.db_user_pass.txt